baseURL: https://come2g.netlify.app/
languageCode: en-us
title: Côme de Germay's Portfolio
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      A FRENCH ENGINEER TRYING TO GET INTO FINANCE.
    title: Hi, my name is Côme
  blog: {}
  contact:
    address:
      - city: London, Greater London
        country: UK
        street: Buckingam Palace
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: cdegermay.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
     - phone: 3630
       title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/cnd3617
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/c%C3%B4me-de-germay/
  image: ''
  name: Côme de Germay
  navigation:
    button1:
      - name: My CV
        url: /pdf/CV C de GERMAY.pdf
    button2:
      - name: HOMNES Invest - Pitch deck
        url: /pdf/HOMNES Invest.pdf
    links:
      - name: Home
        url: '#'
    menu: Menu
    subtitle: at LBS
    title: CGC
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpeg
        subtitle: London Business School - Project 1
        title: Pre-class R project
        url: blogs/ipsum
      - image: House.jpeg
        subtitle: Democratizing real estate through blockchain
        title: HOMNES Invest
        url: https://www.homnesinvest.com
      - image: water.jpeg
        subtitle: Clear water, no compromises 
        title: ThinkTank
        url: https://mcutett-295bc.web.app/
      - image: C++.jpeg
        subtitle: Imperial College London - Project 2
        title: C Compiler & MIPS CPU Emulator
        url: blogs/magna
      - image: fpga.jpeg
        subtitle: Imperial College London - Project 1
        title: Real-time Image Processing on FPGAs
        url: blogs/tempus
      - image: Porto.png
        subtitle: Old portofolio
        title: Portosaurus
        url: https://portosaurus.github.io/ComedeGermaydeC/
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Following my baccalaureate, I decided to pursue a 4-year degree at Imperial College London in Electronics and Computer Science. \n After a first experience in Bouygues Telecom (French carier), 
    I joinded AlixPartners as a strategy consultant, where I was first introduced to finance and its highly intebnse atmosphere. \n It was great but not technical enough for me, hence the next year I joined BNP Paribas in their Risk Division. \n
    Finally, I joined Ardian as a Private Equity intern and loved it, motivating me to work in Corporate Finance.\n, After a brieve attempt to launch my start-up I am looking for new experiences :)" 
    title: Shortned story
    url: blogs
